# Python Overview

This tutorial was written by Terry L. Ruas (University of Wuppertal). The references for external contributors for which this material was anyhow adapted/inspired are in the **Acknowledgments** section (end of the document).

#Python Basics II

This notebook will cover the following topics:

1. Objects
2. Variables with references
3. Duck typing
4. Identity
5. String manipulation
6. String as lists
7. File manipulation I/O
8. Modules and imports
9. Virtual environment


# Objects and Type Redux

Every object in `Python` has a type, but variables are untyped (unless they point to a value).

In [0]:
print(isinstance("Hello", object))
print(isinstance([1,2,3], object))
print(isinstance(42, object))

True
True
True


Each object is also marked with an ID that is used to reference it.

In [0]:
print(id(42))
print(id("mooncake"))

10915808
140009946774640


When talking about variables, they point (reference) to objects, which have a specific ID.

In other words the object ID will be the same one as the variable-ID, because our variables point to the referenced object.

In [0]:
x = 42
y = "cake"

print(id(42))
print(id(x))

print(id("cake"))
print(id(y))



10915808
10915808
140009955730464
140009955730464


When assigning a new  value to a variable, we are actually changing the reference for the object which corresponds (holds) the value.

Think of objects as briefcases with tags. The content of your briefcase is the value, and the tag is the reference to it. When we do `x=y` we are actually changing the tags of our briefcases.

In [0]:
x = 42
y = "cake"

print("Before")
print("X's ID: ",id(x))
print("y's ID: ",id(y))

x=y

print("After")
print("X's ID: ",id(x))
print("Y's ID: ",id(y))

Before
X's ID:  10915808
y's ID:  140009955730464
After
X's ID:  140009955730464
Y's ID:  140009955730464


# Duck Typing

Duck typing is a type system used in dynamic languages, in which do not actually the types any give moment. Instead, we verify the presence of an attribute or method.

Take a look at the function below.

In [0]:
def compute(a,b,c):
  return(a+b)*c

Regardless of the data type we have in `a`,`b`,and `c` we will concatenate the first two and multiply its result according to the last.

In [0]:
print(compute(4,1,3))
print(compute([1],[2,3],2))
print(compute('l','olo', 4))

15
[1, 2, 3, 1, 2, 3]
lolololololololo


However, remember that to overload `+`, the data types must respect the fundamental rule. Thus if we try to combine `int` and a `str` things won't work.

In [0]:
print(compute(1,'cake', 2))

TypeError: ignored

# Identity
When checking for identities, make sure to verify what exactly is being compared. As in any programming languages, `Python` also has its [precedence evaluation](https://docs.python.org/3/reference/expressions.html#operator-precedence).

In [0]:
print(4>3)
print(not True)

True
False


In [0]:
4>3 is not True # how false is true? 

True

In [0]:
(4>3) is (not True) #let's fix that ordering

False

# String Manipulation
Aside from the list operations we can do with strings, there are some functions in the class that con be used as well.

Take a quick look in the previous tutorial to review the single-quotes and double-quotes difference.

In [0]:
print('doesn\'t') 		            # => doesn't 
print("doesn't")                # => doesn't
print('"Yes," he said.') 	    	# => "Yes," he said.
print("\"Yes,\" he said.") 		  # => "Yes," he said.
print('"Isn\'t," she said.') 		# => "Isn't," she said.


doesn't
doesn't
"Yes," he said.
"Yes," he said.
"Isn't," she said.


In [0]:
greeting = "Hello world! "

print('world' in greeting)             # => True
print(len(greeting))                   # => 13
print(greeting.find('lo'))             # => 3 (-1 if not found)
print(greeting.replace('llo', 'y'))    # => "Hey world!"
print(greeting.startswith('Hell'))     # => True
print(greeting.isalpha())              # => False (due to '!')


True
13
3
Hey world! 
True
False


## String as Lists
Some functions allow us to manipulate strings as lists

`split` partitions a string by a delimiter. If no delimiter is provided whitespaces are considered.


In [0]:
print('ham cheese bacon'.split())     # => ['ham', 'cheese', 'bacon']


['ham', 'cheese', 'bacon']


In [0]:
print('03-30-2016'.split(sep='-'))    # => ['03', '30', '2016’]


['03', '30', '2016']


`join` creates a string from a list (of strings)


In [0]:
print(', '.join(['Eric', 'John', 'Michael'])) # => "Eric, John, Michael"


Eric, John, Michael


## Placeholders
We can format strings (including when printing them) by using the `format()` function and its placeholders

In [0]:
# Curly braces in strings are placeholders
print('{} {}'.format('monty', 'python')) # => 'monty python'


monty python


In [0]:
# Provide values by position or by placeholder
print("{0} can be {1} as {0}s".format("strings", "formatted"))# position index
print("{name} loves {food}".format(name="Sam", food="potatoes")) # named place holder


strings can be formatted as stringss
Sam loves potatoes


In [0]:
# Pro: Values are converted to strings (we are not concatenating here, so it is fine)
print("{} squared is {}".format(5, 5 ** 2))


5 squared is 25


### Padding
Wen can fill positions by padding them.

In [0]:
# Padding is just another specifier.
print('{:10}:)'.format('left'))      # => 'left '
print('{:*^12}'.format('KCCS')) # => '****KCCS****' #there are 12 charactes here



left      :)
****KCCS****


# File I/O
The function `open()` allow us to open and read a given file when the path is specified.

At the end of every open-file you must remember to close it, otherwise it will be open "forever"!

In [0]:
f = open("_data/knights.txt")

for line in f:
    data = line.split(' ')
    name = data[0]
    wins = int(data[1])
    losses = int(data[2])
    win_percent = 100 * wins / (wins + losses)
    print(f"{name}: Wins {win_percent:.2f}%")
#f.close() #<- Why not including this is a bad thing?

Lancelot: Wins 66.67%
Galahad: Wins 36.84%
Geraint: Wins 75.00%
Mordred: Wins 84.62%


Another way of opening your files is is the folloiwing constructions

In [0]:
with open('_data/knights.txt', 'r') as f:
  for line in f:
    data = line.split(' ')
    name = data[0]
    wins = int(data[1])
    losses = int(data[2])
    win_percent = 100 * wins / (wins + losses)
    print(f"{name}: Wins {win_percent:.2f}%")
print("File closed: ", f.closed) # => True


Lancelot: Wins 66.67%
Galahad: Wins 36.84%
Geraint: Wins 75.00%
Mordred: Wins 84.62%
File closed:  True


# Modules
It is very likely that `Python` has a library (and Modules) to help you in a given task. 

To use installed modules make sure to `import` them.

In [0]:
import math
num = 25
print(math.sqrt(num))

5.0


Import specific symbols from a module into the local namespace


In [0]:
from math import ceil, floor # we are specifying which modules will be used.
print(ceil(3.7))# => 4.0
print(floor(3.7)) # => 3.0

4
3


Bind module symbols to a new symbol in the local namespace
```py
from some_module import super_long_symbol_name as short_name
```


In [0]:
import numpy as np #This happens very often!

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]



Any python file (including those you write) is a module
```py
from my_file import my_function, my_variable
```


# Virtual Environment

Local, isolated Python environment for interpreter, third-party libraries, and scripts

Each project can have a specific requirement of a library

For example, let us say we have three projects in our system.

1. Project 1 uses NumPy 1.18
2. Project 1 uses NumPy 0.9.8
3. Project 1 uses NumPy 1.16.1



However, our system uses NumPy 1.10.3.
* `/usr/bin/python has numpy 1.10.3`

If we change/update the version in our base system, it will affect all the other components using this library. So we should be able to create separate environments for each project.

Virtual environments allow multiple versions of the same libraries to co-exist.

Please refer to our `00_Environment.ipynb` on how to setup a virtual environment in your notebooks.

For a proper virtual environment setup we recommend this [post](https://medium.com/@rahul3012_37725/a-very-basic-guide-to-python-virtual-environments-a53d1e191490) and the [official documentation](https://docs.python.org/3/library/venv.html).



#Acknowledgements

* Redmond, Hsu, Saini, Gupta, Ramsey, Kondrich, Capoor, Cohen, Borus, Kincaid, Malik, and many others. - Stanford CS41 and CS231n

* Justin Johnson - University of Michigan